WebAppGroup1/Models/Tracker.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAppGroup1.Models
{
	public class Tracker
	{
		[Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Week is required")]
        [MaxLength(1)]
        public int Week { get; set; }
        public string? Stop { get; set; }
        public string? Start { get; set; }
        public string? Continue { get; set; }
        public string? Comments { get; set; }

        [Required(ErrorMessage = "Technical Skill is required")]
        [Display(Name = "Technical Skill")]
        public string TechnicalSkill { get; set; } = null!;

        [Required(ErrorMessage = "Soft Skill is required")]
        [Display(Name = "Soft Skill")]
        public string SoftSkill { get; set; } = null!;
        public bool Complete { get; set; } = false;
        public Spartan? Spartan { get; set; }

        [ValidateNever]
        [ForeignKey("Spartan")]
        public string SpartanId { get; set; } = null!;

		public string? Owner { get; set; }
	}
}

WebAppGroup1/Controllers/TrackersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppGroup1.Data;
using WebAppGroup1.Models;
using WebAppGroup1.Models.ViewModels;
using WebAppGroup1.Services;

namespace WebAppGroup1.Controllers
{
    [Authorize]
    public class TrackersController : Controller
    {
        private readonly ITrackerService _service;

        public TrackersController(ITrackerService service)
        {
            _service = service;
        }

        [Authorize(Roles = "Trainee, Trainer")]
        // GET: Trackers
        public async Task<IActionResult> Index(string filter = null)
        {
            var user = await _service.GetUserAsync(HttpContext);
            var response = await _service.GetTrackerEntriesAsync(user.Data, _service.GetRole(HttpContext), filter);

            return response.Success ? View(response.Data) : Problem(response.Message);
        }

        [Authorize(Roles = "Trainee, Trainer")]
        // GET: Trackers/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            var currentUser = await _service.GetUserAsync(HttpContext);
            var response = await _service.GetDetailsAsync(currentUser.Data, id, _service.GetRole(HttpContext));
            return response.Success? View(response.Data) : Problem(response.Message);

        }

        // GET: Trackers/Create
        [Authorize(Roles = "Trainee")]

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Trainee")]

        public async Task<IActionResult> Create(TrackerCreateVM trackerCreateVM)
        {

            var currentUser = await _service.GetUserAsync(HttpContext);
            var response = await _service.CreateTrackerEntriesAsync(currentUser.Data, trackerCreateVM);
            return response.Success ? RedirectToAction(nameof(Index)) : View(trackerCreateVM);
        }

        // GET: Trackers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Trainee")]
        public async Task<IActionResult> Edit(int id, TrackerEditVM trackerEditVM)
        {
            var currentUser = await _service.GetUserAsync(HttpContext);
            var response = await _service.EditTrackerEntriesAsync(currentUser.Data, id, trackerEditVM);
            return response.Success ? RedirectToAction(nameof(Index)) : Problem(response.Message);
        }

        // POST: Trackers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpGet]
        [Authorize(Roles = "Trainee")]

        public async Task<IActionResult> Edit(int? id)
        {
            var currentUser = await _service.GetUserAsync(HttpContext);
            var response = await _service.GetEditDetailsAsync(currentUser.Data, id);
            return response.Success ? View(response.Data) : NotFound();
        }

        // GET: Trackers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Trainee")]

        public async Task<IActionResult> Delete(int? id)
        {

            var currentUser = await _service.GetUserAsync(HttpContext);
            var response = await _service.DeleteTrackerEntriesAsync(currentUser.Data, id);
            return response.Success ? RedirectToAction(nameof(Index)) : Problem(response.Message);
        }

        //UpdateTrackerComplete

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Trainer")]

        public async Task<IActionResult> UpdateTraineeTrackerComplete(int id, MarkCompleteVM markCompleteVM)
        {
            var currentUser = await _service.GetUserAsync(HttpContext);
            var response = await _service.UpdateTrackerEntriesCompleteAsync(currentUser.Data, id, markCompleteVM, _service.GetRole(HttpContext));
            return response.Success ? RedirectToAction(nameof(Index)) : Problem(response.Message);

        }
    }


}

WebAppGroup1/Views/Trackers/Create.cshtml
@model WebAppGroup1.Models.ViewModels.TrackerCreateVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Tracker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Week" class="control-label"></label>
                <select asp-for="Week" name="Week" class="form-select">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                </select>
                <span asp-validation-for="Week" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stop" class="control-label"></label>
                <textarea asp-for="Stop" class="form-control" rounded-0" rows="10"></textarea>
                <span asp-validation-for="Stop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <textarea asp-for="Start" class="form-control" rounded-0" rows="10"></textarea>
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Continue" class="control-label"></label>
                <textarea asp-for="Continue" class="form-control" rounded-0" rows="10"></textarea>
                <span asp-validation-for="Continue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <textarea asp-for="Comments" class="form-control" rounded-0" rows="10"></textarea>
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TechnicalSkill" class="control-label"></label>
                <select asp-for="TechnicalSkill" name="TechnicalSkill" class="form-select">
                    <option value="Skilled">Skilled</option>
                    <option value="Partially Skilled">Partially Skilled</option>
                    <option value="Low Skilled">Low Skilled</option>
                    <option value="Unskilled">Unskilled</option>
                </select>
                <span asp-validation-for="TechnicalSkill" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoftSkill" class="control-label"></label>
                <select asp-for="SoftSkill" name="SoftSkill" class="form-select">
                    <option value="Skilled">Skilled</option>
                    <option value="Partially Skilled">Partially Skilled</option>
                    <option value="Low Skilled">Low Skilled</option>
                    <option value="Unskilled">Unskilled</option>
                </select>
                <span asp-validation-for="SoftSkill" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAppGroup1/Views/Trackers/Details.cshtml
@model WebAppGroup1.Models.ViewModels.TrackerDetailsVM

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Tracker - @Html.DisplayFor(model => model.Owner)</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Week)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Week)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stop)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Start)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Start)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Continue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Continue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comments)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TechnicalSkill)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TechnicalSkill)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoftSkill)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoftSkill)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebAppGroup1/Views/Trackers/Edit.cshtml
@model WebAppGroup1.Models.ViewModels.TrackerEditVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Tracker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @*<div class="form-group">
            <label asp-for="Week" class="control-label"></label>
            <input asp-for="Week" class="form-control" />
            <span asp-validation-for="Week" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Week" class="control-label"></label>
                <select asp-for="Week" name="Week" class="form-select">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                </select>
                <span asp-validation-for="Week" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stop" class="control-label"></label>
                <textarea asp-for="Stop" class="form-control" rounded-0" rows="10"></textarea>
                <span asp-validation-for="Stop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <textarea asp-for="Start" class="form-control" rounded-0" rows="10"></textarea>
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Continue" class="control-label"></label>
                <textarea asp-for="Continue" class="form-control" rounded-0" rows="10"></textarea>
                <span asp-validation-for="Continue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <textarea asp-for="Comments" class="form-control" rounded-0" rows="10"></textarea>
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TechnicalSkill" class="control-label"></label>
                <select asp-for="TechnicalSkill" name="TechnicalSkill" class="form-select">
                    <option value="Skilled">Skilled</option>
                    <option value="Partially Skilled">Partially Skilled</option>
                    <option value="Low Skilled">Low Skilled</option>
                    <option value="Unskilled">Unskilled</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="SoftSkill" class="control-label"></label>
                <select asp-for="SoftSkill" name="SoftSkill" class="form-select">
                    <option value="Skilled">Skilled</option>
                    <option value="Partially Skilled">Partially Skilled</option>
                    <option value="Low Skilled">Low Skilled</option>
                    <option value="Unskilled">Unskilled</option>
                </select>
            </div>
            <div class="form-group" id="editsavebtn">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebAppGroup1/Views/Trackers/Index.cshtml
@model IEnumerable<WebAppGroup1.Models.ViewModels.TrackerVM> 

@{
	ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
	<a asp-action="Create">Create New</a>
</p>

<form asp-controller="Trackers" asp-action="Index" method="get">
	<p>
		<label for="filter">Filter by: </label>
		<input type="text" id="filter" name="filter" />
		<button type="submit" class="btn btn-outline-info">Filter</button>
	</p>
</form>

<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Owner)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Week)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.TechnicalSkill)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.SoftSkill)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Complete)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Owner)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Week)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.TechnicalSkill)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.SoftSkill)
				</td>
					<td>
						<form asp-action="UpdateTraineeTrackerComplete" asp-route-id="@item.Id">
						@Html.CheckBox("Complete", item.Complete, new {onChange="this.form.submit()"})
					</form>
					</td>
				<td class="btn-group-horizontal">
					<a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Edit</a>
					<a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Details</a>

					<a class="btn btn-danger">
						@using (Html.BeginForm("Delete", "Trackers", new { id = item.Id }))
						{
							<input type="submit" class="bg-transparent border-0" value="Delete" onclick="return confirm('Are you sure you wish to delete the Tracker for week @item.Week?')" />
						}
					</a>
				</td>
			</tr>
		}
	</tbody>
</table>

<div class="justify-content-center">
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	<script type="text/javascript">
		google.charts.load("current", { packages: ["corechart"] });
		google.charts.setOnLoadCallback(drawChart);
		function drawChart() {
			var data = google.visualization.arrayToDataTable([
				['Status', 'Number'],
				['Complete', @Model.Where(x => x.Complete).Count()],
				['Incomplete', @Model.Where(x => !x.Complete).Count()]
			]);

			var options = {
				title: 'Tracker Entry Completion',
				pieHole: 0.4,
			};

			var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
			chart.draw(data, options);
		}
	</script>
</div>
<div class="justify-content-center">
	<div class="justify-content-center" id="donutchart" style="width: 900px; height: 500px;"></div>
</div>